# Generated by Django 4.1.2 on 2022-12-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_comentarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
