# Generated by Django 4.1.2 on 2022-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0004_alter_comentarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='usuario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
