# Generated by Django 4.1.2 on 2022-12-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0005_blogs_usuario_alter_comentarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='idblog',
            field=models.CharField(max_length=5),
        ),
    ]
