# Generated by Django 4.1.2 on 2022-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0006_alter_comentarios_idblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='idblog',
            field=models.IntegerField(),
        ),
    ]
