# Generated by Django 4.1.2 on 2022-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0008_remove_mensajes_iddestinatario_mensajes_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='autor',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
